# importing numpy and array formation 

numpy library can be used to convert list to arrays of multidimensions and work with them.

In [1]:
import numpy as np 

a = np.array([1,2,3]) #creating an array using np and array function . this takes a list
print(type(a)) #this is an array from numpy
print(a.shape) 


<class 'numpy.ndarray'>
(3,)


In [2]:
print(a[0] , a[1], a[2]) #individual nubers in array

1 2 3


In [3]:
a[0] = 5*5
print(a)

[25  2  3]


# multple dimension array

the above exapmle was 1d array. 
similarily we can have nd array

In [5]:
b = np.array([[1,2,3] ,[-1,-2,-3]]) #remember here to use 2 time [] brackets
print(type(b))                      #we created a 2*3 array. 2rows and 3 columns
print(b.shape)

<class 'numpy.ndarray'>
(2, 3)


In [6]:
print(b)

[[ 1  2  3]
 [-1 -2 -3]]


In [7]:
#taking individuals just as indexing
print(b[0,0])
print(b[1,2])

1
-3


# special array

now numpy has the ability to create certain special arrays on its own.
these are shown below

In [15]:
a = np.zeros((2,2))    #create a 2*2 array with all elements as 0
print('a:\t', a)

b= np.zeros((5,2))
print('b:\t',b)


c= np.ones((3,4)) #all elements 1
print('c:\t',c)


d = np.full((2,2),7)  #creates a 2*2 array with all elements being constant as 7
print('d:\t',d)


e = np.eye(2)   #create a 2*2 identity array. only need to give 2 and not just 2*2
print('e:\t' ,e)


f = np.random.random((2,2)) #create by taking random numbers
print('f:\t',f)

a:	 [[0. 0.]
 [0. 0.]]
b:	 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
c:	 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
d:	 [[7 7]
 [7 7]]
e:	 [[1. 0.]
 [0. 1.]]
f:	 [[0.77999924 0.09383504]
 [0.694162   0.29402476]]


# slicing in array

In [19]:
import numpy as np

a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]]) #3*4 array
print(a)

# slicing a the array and taking it in another array 
# taking 2*2 from a array.
# 1,2
# 5,6
b = a[:2 ,1:3]
print(b)



#one important thing to remember is that changing any element of b will also change a
#as b is just a active subset of a
b[1,1] = 12
print(b)

print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2]
 [5 6]]
[[ 1  2]
 [ 5 12]]
[[ 0  1  2  3]
 [ 4  5 12  7]
 [ 8  9 10 11]]


another way  of indeing and explanation about shape and rank

In [23]:
import numpy as np

a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

#suppose we want to take 2nd row all elements
a1 = a[1,:]
print(a1)

a2 = a[1:2,:]
print(a2)

print(a1.shape)
print(a2.shape)

[4 5 6 7]
[[4 5 6 7]]
(4,)
(1, 4)


if we notice that shpae of a1 and a2, we notice difference as (4,) and (1,4)
this (4,) indicates al lower rank
(1,4) indicates a higher rank

In [24]:
#similarily for column
#taking 2nd column

b1 = a[:,1 ]
print(b1)
print(b.shape)

b2 = a[:,1:2]
print(b2)
print(b2.shape)


[1 5 9]
(2, 2)
[[1]
 [5]
 [9]]
(3, 1)


# integer array indexing and slicing

In [27]:
#slicing
import numpy as np
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print(a)

#slicing is using simple [:,:]
#suppose we want [1,6,9]

a1 =np.array([a[0,1],a[1,2],a[2,1]])
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 6 9]


integer indexing is done in a diffrent way

In [29]:
b1 = a[[0,1,2],[1,2,1]]
print(b1)
#the first [0,1,2] indicates the rows from which we want to take elements, here it is row 0,1,2
#the second [1,2,1] indicates the column from which the elemt has to be taken

[1 6 9]


In [30]:
#suppose we want 2,2 from a
b2 = a[[0,0],[1,1]]
print(b2)

[1 1]


another way of doing this 

In [32]:
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,41,15]])
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 41 15]]


In [40]:
#if we want 2,5,11,41 through integer indexing
#1st way

a1 = a[[0,1,2,3],[2,1,3,2]]
print(a1)

#2nd way
#instead of using [0,1,2,3] we can use [np.arange(4)]  which will gives us same result
#and instead of [2,1,3,2] we can create an array b and use b

b = np.array([2,1,3,2])

a2 = a[np.arange(4),b]
print(a2)

[ 2  5 11 41]
[ 2  5 11 41]


# mutting elements

In [41]:
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,41,15]])
print(a)

b =np.array([2,1,1,3])


a[np.arange(4),b] += 10

print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 41 15]]
[[ 0  1 12  3]
 [ 4 15  6  7]
 [ 8 19 10 11]
 [12 13 41 25]]


# boolean array indexing

In [46]:
#we can use booleans to construct a array from another array

a = np.array([[0,1],[2,3],[4,5]])
print(a)

#we form an aray from boolean with a condition

b1 = (a>2)
print(b1) #this gives the same dimension array with true or false

#now we use this b1 to construct a 1d array

a1 = a[b1]
print(a1)

#this can be dne in one step
print(a[(a>2)])

[[0 1]
 [2 3]
 [4 5]]
[[False False]
 [False  True]
 [ True  True]]
[3 4 5]
[3 4 5]


# Datatypes

when we form an array, it itself determines the datatypes f the array
we can also tell the program tomuse the particular data types

In [49]:
import numpy as n

a = np.array([1,2])
print(a.dtype)

b = np.array([1.0,2.0])
print(b.dtype)

#we can change the dattype on our owns

a1 = np.array([1,2] ,dtype = np.int64)
print(a1.dtype)

int32
float64
int64


# math operation
basi math operation array can be performed either through operator or function in numpy

In [58]:
a =np.array([[1,2],[3,4]])
b =np.array([[5,6],[0,7]])

print(a+b) #using operator
print(np.add(a,b)) #using np.add function in numpy

print(a-b)
print(np.subtract(a,b))

#the multiplicati here is elementwise multiplication and not matrix multipliaction
print(a*b)
print(np.multiply(a,b))

print(a/b)
print(np.divide(a,b))

print(np.sqrt(a))

[[ 6  8]
 [ 3 11]]
[[ 6  8]
 [ 3 11]]
[[-4 -4]
 [ 3 -3]]
[[-4 -4]
 [ 3 -3]]
[[ 5 12]
 [ 0 28]]
[[ 5 12]
 [ 0 28]]
[[0.2        0.33333333]
 [       inf 0.57142857]]
[[0.2        0.33333333]
 [       inf 0.57142857]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in true_divide
  del sys.path[0]
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in true_divide
  
